### ISSUE TITLE
政府標準利用規約をテンプレートではなくリンクのみにしてはどうでしょう？

### ISSUE THREAD

**Issue by taisukef** [code4fukui/copyright-policy-jp#2]
現在の[政府標準利用規約](https://github.com/code4fukui/copyright-policy-jp/blob/main/%E6%94%BF%E5%BA%9C%E6%A8%99%E6%BA%96%E5%88%A9%E7%94%A8%E8%A6%8F%E7%B4%84(%E7%AC%AC2.0%E7%89%88).md)はそれを元に各省庁自治体がそれぞれ作成する形になっています
CC BY や、ODbLなどと同様、リンクするだけの形にするとよりシンプルで広がりやすそうです

**Comment by mapconcierge** [comment]
GitHub の LICENSE.md ファイルとして利用できるテンプレートが実用的ですね。

**Comment by taisukef** [comment]
テンプレート型でいきましょう
