### ISSUE TITLE
和暦表記を西暦表記に

### ISSUE THREAD

**Issue by ymgt-design** [code4fukui/copyright-policy-jp#6]
せっかくなので和暦表示の部分を西暦に変更していきたいですね

**Comment by taisukef** [comment]
西暦にしましょう！

**Comment by mapconcierge** [comment]
賛成です！

**Comment by taisukef** [comment]
西暦表示となりました！
https://github.com/mapconcierge/copyright-policy-jp/blob/main/OpenDataStandardTermsofUse/LICENSE.md
